Applied code checks
itom-project/itom pull request #284
Opened 2024-04-26 06:02 UTC by photoniker

I have applied checks and fixes onto the source code using pre_commit hooks:
- pyupgrade
- codespell
- fix-byte-order-marker

2024-04-27 18:24 UTC, photoniker reviewed
I didn't find something

2024-04-28 21:32 UTC, magro11 requested changes
Please check my inline-comments. Especially make sure, that gtest is not changed and set to exclude list and make sure, that PyQT6-auto-generated ui.py files will not be generated any more and will be removed.

2024-04-28 21:32 UTC, magro11 commented on docs/docsTmpl/sphinxext/docscrape.py
> +# from StringIO import StringIO
remove this line

2024-04-28 21:32 UTC, magro11 commented on itom-packages/apps/roughnessEvaluator/profile_roughness.py
> +                "Value and horizontal axis unit must be nm, �m or mm",
the special character should be µm, if the file is stored as utf8. Please check this (e.g. with notepad++). Check encoding and that the µ-sign is correct.

2024-04-28 21:32 UTC, magro11 commented on itom-packages/devices/Axiovert200M/simpleGUI_ui.py
remove this file and make sure, that PyQt6 uic is not compiling any ui-files to python files

2024-04-28 21:32 UTC, magro11 commented on itom-packages/devices/thorlabsLabJack/MLJ050.py
> +        # Acceleration (36 a6 01 00) = 108086 -> *90.9 wegen komischem Factor = 9825017.4 -> ca. 7.99 mm/sec/sec (durch 1228800 microsteps)
translate this line and the next one to english

2024-04-28 21:32 UTC, magro11 commented on itom-packages/itomAlgorithmsStubsGen.py
> +    header = """# coding=iso-8859-15
I would say, that this ```coding=iso-...``` line can be removed. Remove the string ```# coding=iso-8859-15```

2024-04-29 07:17 UTC, photoniker commented on .codespell_ignore_words.txt
> +marge
Manuel is an author named in some file. Marge is from Simpsons used in an example

2024-04-29 07:20 UTC, photoniker commented on Qitom/translation/qitom_zh.ts
> -        <source>Base path for relative pathes: </source>
But still pathes is wrong?!

2024-04-29 09:37 UTC, photoniker commented
For python unittest I see such fails: 

- dataobject_np_conversion.py:
`======================================================================
FAIL: test_continuousDataObject2NpArray 
... (dataobject_np_conversion.DataObjectNpConversion.test_continuousDataObject2NpArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\itom\sources\itom\python_unittests\dataobject_np_conversion.py", line 24, in 
... test_continuousDataObject2NpArray
    self.assertIs(b1.base, a)
AssertionError: (dataObject('uint8', [2 x 3 x 3], continuous: 1, owndata: 1), <capsule object NULL at 
... 0x000002D908301B00>) is not dataObject('uint8', [2 x 3 x 3], continuous: 1, owndata: 1)`

- itom_jedilib.py:
`======================================================================
FAIL: test_help_notypehints (itom_jedilib.ItomJediLibTest.test_help_notypehints)
.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\itom\sources\itom\python_unittests\itom_jedilib.py", line 229, in test_help_notypehints
    self.assertEqual(len(h), 0)
AssertionError: 1 != 0`

2024-05-02 07:43 UTC, BBertschinger commented
Do we have a documentation on how to apply our pre-commit hooks?

2024-05-02 09:05 UTC, photoniker commented
@BBertschinger see into the README of https://github.com/itom-project
![image](https://github.com/itom-project/itom/assets/17592823/0c3c8f01-c863-4dfa-aff4-015a2b6d8188)

2024-05-10 18:31 UTC, merged